### ISSUE TITLE
Memory leak problem

### ISSUE THREAD

**Issue by AlexTasev** [zulucoda/react-swift-slider#7]
Hello,

I tried "react-swift-slider" and it's very nice and easy to use for a beginner with React like me. The issue appears when I use it as image slider on the home page of my app and the following error appears when I go to another page:

"Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in Slider (at Home.jsx:57)".

I see in the task manager that Google Chrome is using almost all of my RAM and the used memory increases with time, which means that memory leak really happens. Probably in componentWillUnmount method the interval should be cleared and this could solve the problem.

**Comment by AlexTasev** [comment]
I fixed the problem by conditional rendering:
{
     this.state.mountedHome ? <SwiftSlider data={this.state.data} showDots={false} /> : null
},
where "mountedHome" is set to true in componenDidMounnt and to false in componentWillUnmount method.

It will be good to fix it in the lib itself.

Best regards,
Alex

[Home.zip](https://github.com/zulucoda/react-swift-slider/files/3003953/Home.zip)

**Comment by AlexTasev** [comment]
Actualy the fix mentioned above does not work and I discovered it on another PC with no node modules. The working fix is in the lib itself in Slider class, between componentDidMount and render methods:

{
      key: "componentWillUnmount",
      value: function componentWillUnmount() {
        this.setState({
          slideInterval: clearInterval(this.state.slideInterval)
        });
      }
    },

**Comment by zulucoda** [comment]
Hi @AlexTasev

Thank you for using `react-swift-slider` — apologies for only getting back to you now (Somehow I didnt get an email from GitHub when this issue was logged :confused: ). I will have a look at this issue.

Thank you again for the detailed description of the problem; this will help me with resolving this issue.

I am planning on updating the slider to use new React features, so look out for those updates soon.

Cheers
Muzi

**Comment by zulucoda** [comment]
Hi @AlexTasev 

This issue has been resolved in the new version. Therefore I'm going to close this issue.

Please, will you kindly advise if you have any other issues.

Cheers
Muzi
